version: "3.8"
services:
  flask-agent:
    build:
      context: ./flask-agent
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - flask-agent
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
