version: '3.8'

services:
  backend:
    container_name: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  ai-agent:
    container_name: flask-ai-agent
    build:
      context: ./ai-agent
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - ai-agent
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
