version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  ai-agent:
    build: ./ai-agent
    ports:
      - "5000:7860"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - ai-agent
