version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  ai-agent:
    build: ./ai-agent
    ports:
      - "5000:7860"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - ai-agent