name: Helm Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.8.0'

      - name: Helm Upgrade
        run: |
          helm upgrade --install llm-stack ./llm-stack \
            --namespace llm --create-namespace \
            --values ./llm-stack/values.yaml
